### ISSUE TITLE
[优先级高]小程序  文章发布之后的确认流程不够清晰 

### ISSUE THREAD

**Issue by dutLyuyu** [bingtsingw/nanmu-issues#3]
## 问题
1. 广场的排序好像不是最新的发布在最前。去小程序确认”自己文章是否发布成功“，如果需要增加操作：去下滑到底部，或者是点击到”我的“ -> ”我的作品“并不方便。
2. 确认发布是否成功如果是靠“我的”下的”我的作品“页面的话。“我的作品”应该具备点击看到详细的内容和点赞情况的功能。这作为确认流程的一环，还是蛮重要的。
3. 同上，“我的” -> "我的作品"， UI上没有很强的点击引导。也许可以参考微信的“我的”页面。

![1281632136413_ pic](https://user-images.githubusercontent.com/40752791/133994889-12ca6d87-1e90-4b67-81d5-f020c815ebe1.jpg)

### 1.的解决方法：
我觉得最简单的应该是广场排序 默认成最新的发布在最前。
或者
每次打开页面，如果最近5分钟之内自己发布过作品，弹出popup，让用户选择直接一键跳转到”我的作品“页面。

###  2的解决方法
“我的作品”应该具备点击看到详细的内容和点赞情况的功能。这作为确认流程的一环，还是蛮重要的。

###  3的解决方法
参考微信的“我的”页面，

**Comment by bingtsingw** [comment]
谢谢建议, 均已修复
1. 没有做popup, 改了默认排序
2. 我的作品不能点击是个bug, 已修复
3. 已添加图标指引
